### ISSUE TITLE
In admin, remove "License Info" page

### ISSUE THREAD

**Issue by jonyo** [geodesicsolutions-community/geocore-community#111]
The page should be removed.  The current solution was very quick hack, but it leaves the old buttons and everything.  Probably don't need the page anymore at all.

**Comment by vicos59** [comment]
I'll take a stab at this now.

**Comment by vicos59** [comment]
- [ ] src\admin\admin_classauction_tools.php
- [ ] src\admin\menus\sections\admin_tools.php
- [ ] src\admin\templates\licenseInfo.tpl

**Comment by vicos59** [comment]
@jonyo Would you please check src\admin\menus\sections\admin_tools.php

That file and most/many/several of the other in that dir do not close the <?php ?> tag at the bottom of the file.

Is it supposed to be this way? or did something go horribly wrong once beofre?

**Comment by jonyo** [comment]
> @jonyo Would you please check src\admin\menus\sections\admin_tools.php
> 
> That file and most/many/several of the other in that dir do not close the `<?php ?>` tag at the bottom of the file.
> 
> Is it supposed to be this way? or did something go horribly wrong once before?

Just reading this.

About the closing `?>` tag - yes it is normal to leave that off of "code only" files (which means almost all of the files since the software uses Smarty templates currently), and in fact is recommended to avoid inadvertently inserting extra white space on the page before you mean to.  Which is not good if you want to set a cookie or something, you can't if some whitespace is already sent.

**Comment by jonyo** [comment]
See also: see the notes at the bottom of the [php tags documentation](https://www.php.net/manual/en/language.basic-syntax.phptags.php)
