### ISSUE TITLE
Legacy Changelogs: Either update or remove altogether

### ISSUE THREAD

**Issue by vicos59** [geodesicsolutions-community/geocore-community#143]
> There are also many changelogs with 'geodesicsolutions.com' which I elected not to list above.
> 
> Do we care?

Hmm, so the links all go to the old bugzilla bug tracker.  A few years back when Geo was still around and they contracted me to help recover the database, the bug tracker was one that was completely corrupted.  And if I remember correctly, it was behind a login, so it won't show up in wayback.

So I say...  Maybe make a short page in the wiki saying something like the above, that the old bug tracker was corrupted and no longer available so the advanced details for each issue is lost.  Then change the links to go there.

It may be a big enough of a task to be its own PR / issue.

_Originally posted by @jonyo in https://github.com/geodesicsolutions-community/geocore-community/issues/120#issuecomment-1059792467_

**Comment by vicos59** [comment]
Many of the old affiliate banners we removed from the template sets are referenced in the changelogs.

**Comment by vicos59** [comment]
@jonyo I am confused about these changelogs. I see they are in the upgrade/versions folders. I understand that the other files are used to upgrade between versions, but do the html files serve any real purpose? The entire upgrade folder is removed after installation.

If the changelogs are on the .org website and the ones in the code point to an obsolete bugzilla, is there any point in keeping them?

**Comment by jonyo** [comment]
@vicos59 They exist in the code set and on the website.  In the upgrade I think we link to the changlogs "locally".

I'd be fine with removing them from the codebase if that is how you want to handle it, just need to be sure any links into them (if there are any) are updated.
