### ISSUE TITLE
install error on 20.0.0 BETA 3 - Full Release - Community Edition

### ISSUE THREAD

**Issue by Genovit** [geodesicsolutions-community/geocore-community#157]
install error on 20.0.0 BETA 3 - Full Release - Community Edition
Hi my sever is on godaddy.com im running php7.4.28
the install ran grait untill i clicked on the admin link and got the following error on page: any help would be great!

Error: Call to undefined method mysqli_stmt::get_result() in /home/public_html/copylathe/Machine_Post/vendor/adodb/adodb-php/drivers/adodb-mysqli.inc.php:1265
Stack trace:
#0 /home/public_html/copylathe/Machine_Post/vendor/adodb/adodb-php/adodb.inc.php(1539): ADODB_mysqli->_query('SELECT `setting...', Array)
#1 /home/public_html/copylathe/Machine_Post/vendor/adodb/adodb-php/drivers/adodb-mysqli.inc.php(1135): ADOConnection->_Execute('SELECT `setting...', Array)
#2 /home/public_html/copylathe/Machine_Post/classes/php5_classes/DataAccess.class.php(262): ADODB_mysqli->execute('SELECT `setting...', Array)
#3 /home/public_html/copylathe/Machine_Post/classes/php5_classes/DataAccess.class.php(941): DataAccess->Execute('SELECT `setting...', Array)
#4 /home/public_html/copylathe/Machine_Post/classes/php5_classes/products.php(2385): DataAccess->get_site_setting('additional_robo...', true)
#5 /home/public_html/copylathe/Machine_Post/classes/php5_classes/products.php(1809): geoSession->is_robot()
#6 /home/public_html/copylathe/Machine_Post/classes/php5_classes/products.php(1936): geoSession->_newSession()
#7 /home/public_html/copylathe/Machine_Post/admin/app_top.admin.php(59): geoSession->initSession()
#8 /home/public_html/copylathe/Machine_Post/admin/index.php(5): require_once('/home/...')
#9 {main}

**Comment by vicos59** [comment]
Can you verify that the server has mysqli configured for PHP? I had a similar error when I first built PHP 7.4 on my server and forgot to include the mysqli extension.

Other than that, Beta-3 is pretty old by current standards. If you like I can upload the current snapshot to a file sharing service where you can download it. I don't have privs to create a new distro here on Github.

**Comment by vicos59** [comment]
Here is a link for a snapshot I built on 10-MAR-2022. It is pretty stable with the exception of 2 outstanding bugs which only affect obscure addons, like Bulk uploader.

Other known issues:

-- Facebook Login does not work (at least for me)
-- I have not tested the payment gateways

https://we.tl/t-ZicV9lOTPO

This is stored on https://wetransfer.com/ if you are not familiar with it.

**Comment by Genovit** [comment]
thanks do i do a clean install? or just upload these files to replace what i have upthere?

**Comment by vicos59** [comment]
I don't have the background on what you are doing. So, if you are installing this for the first time on your server, if I it was me, I would probably just start over with a fresh install. Then you eliminate any possibilities for confusion.

I would not attempt to upgrade an existing system until I had installed a fresh test copy on another domain to make sure it works as required in your environment.

I would also stick with the default template set because you can be sure that one will always be updated.

**Comment by Genovit** [comment]
hi i checked my php.info file and this exstention says its off:  

mysqli.allow_local_infile | Off ,,how do i format the php ini file to trun it on?

**Comment by vicos59** [comment]
If you're using GoDaddy, they probably have a control panel. Otherwise, I would search their support FAQ or contact them.

**Comment by vicos59** [comment]
> mysqli.allow_local_infile

BTW, that alone does not mean that mysqli is not enabled, just that one `allow_local_infile` feature. mysqli is typically pretty standard in PHP installations.

**Comment by vicos59** [comment]
Just create a test.php file and put this in it:

<?php

phpinfo();

?>

and run it. It will give you the complete setup for your PHP environment. Then you can look for this:

![mysqli](https://user-images.githubusercontent.com/6634041/159812222-f141afe3-3eea-4730-b371-d1a919e22fdb.JPG)

**Comment by Genovit** [comment]
yup thats what i have ill try installing this afternoon wish me luck thankyou for your help let ya know how i make out

**Comment by Genovit** [comment]
no luck still same error
Error: Call to undefined method mysqli_stmt::get_result()

**Comment by Genovit** [comment]
Error: Call to undefined method mysqli_stmt::get_result() in /home/public_html/copylathe/Machine_Post/vendor/adodb/adodb-php/drivers/adodb-mysqli.inc.php:1265
Stack trace:
#0 /home/public_html/copylathe/Machine_Post/vendor/adodb/adodb-php/adodb.inc.php(1539): ADODB_mysqli->_query('SELECT `setting...', Array)
#1 /home/public_html/copylathe/Machine_Post/vendor/adodb/adodb-php/drivers/adodb-mysqli.inc.php(1135): ADOConnection->_Execute('SELECT `setting...', Array)
#2 /home/public_html/copylathe/Machine_Post/classes/php5_classes/DataAccess.class.php(262): ADODB_mysqli->execute('SELECT `setting...', Array)
#3 /home/public_html/copylathe/Machine_Post/classes/php5_classes/DataAccess.class.php(941): DataAccess->Execute('SELECT `setting...', Array)
#4 /home/public_html/copylathe/Machine_Post/classes/php5_classes/products.php(2385): DataAccess->get_site_setting('additional_robo...', true)
#5 /home/public_html/copylathe/Machine_Post/classes/php5_classes/products.php(1809): geoSession->is_robot()
#6 /home/public_html/copylathe/Machine_Post/classes/php5_classes/products.php(1936): geoSession->_newSession()
#7 /home/public_html/copylathe/Machine_Post/admin/app_top.admin.php(59): geoSession->initSession()
#8 /home/public_html/copylathe/Machine_Post/admin/index.php(5): require_once('/home/...')
#9 {main}

**Comment by Genovit** [comment]
FIXED IT FINALY  With PHP version 7.2 I just used nd_mysqli instead of mysqli and it worked as expected.

Steps to enable it into godaddy hosting server-

    Login to cpanel.
    Click on "Select PHP version".
    As provided the snapshot of the latest configurations uncheck "mysqli" and enable "nd_mysqli".

**Comment by vicos59** [comment]
I was wondering if it had something to do with Godaddy hosting; I know they have their own special way of doing things.

Not sure why it works that way for you. I have no problems running Beta-3 & 4 an the current snapshot with mysqli on PHP 7.2 --> 8.1 on my cPanel server.

Maybe @jonyo will have some insight. Be good to know for other users who use Godaddy. Did you try PHP 7.4 with nd_mysqli?

**Comment by Genovit** [comment]
hi how do you edit the pricing text or page text on pricing page looked everywhere index.php?a=28&b=143

**Comment by vicos59** [comment]
You can see all of these types of pages here:

`/admin/index.php?page=sections_extra_pages&mc=pages_management`

If you click on edit for the pricing page, you can see that it uses the `extra_pages/pricing.tpl` template.

To get to that, you would have to go to `/admin/index.php?page=design_sets&mc=design` and edit templates and drill down until you find that one.

But first, be sure you create your own Main Template Set where you can make edits. If you edit the default set, they will be overwritten next time you upgrade.

Best to read the docs regarding templates before you go too far, so you understand how they work. I know I was pretty confused the first time I used the system.

**Comment by vicos59** [comment]
I'm going to close this issue since the original problem has been resolved. If you have any more questions about using it, just open a new thread in the Discussion area. Keeps things organized for future readers.

**Comment by Genovit** [comment]
thankyou so much
