### ISSUE TITLE
Total Addons Installed/Enabled counter is off by 1/one

### ISSUE THREAD

**Issue by vicos59** [geodesicsolutions-community/geocore-community#160]
![addons count](https://user-images.githubusercontent.com/6634041/160261458-d47926a5-0940-4932-b5da-d61b44b09392.JPG)

![addons count 2](https://user-images.githubusercontent.com/6634041/160261513-369fb872-bb8c-4870-8bca-ffccb0d416e6.JPG)

The count is one higher than it should be. Confirmed in Docker and on my test site.

**Comment by jonyo** [comment]
Fixed by #170
