### ISSUE TITLE
Critical errors upgrading from v7.5.2

### ISSUE THREAD

**Issue by vicos59** [geodesicsolutions-community/geocore-community#187]
@jonyo, I wish I would have run a test upgrade sooner. In any case:

![upgrade screen](https://user-images.githubusercontent.com/6634041/186282577-9eadc2a4-3ed1-4e87-a8f7-29c1dad547cb.JPG)

It fails hard on 7.5.3 -> 7.6.0

![error-1](https://user-images.githubusercontent.com/6634041/186282632-ff5f9f85-006e-4c29-971a-2b5abc39e649.JPG)

From the looks of it, the problem is because mySQL is running in strict mode and thus default values are required for all fields.

**Comment by vicos59** [comment]
So, the table is:

![geodesic_upgrade_queries](https://user-images.githubusercontent.com/6634041/186284373-00a1b066-be5e-4d74-8d41-bf703c69d3dc.jpg)

I updated the table to set the DEFAULT to NULL (which is what you see above. There was no default value before.

Anyway, that moves us along to the next error:

![error-2](https://user-images.githubusercontent.com/6634041/186284740-83cb0ba7-0e8d-489f-9cae-e534e23442fb.jpg)

This is the statement that is trying to execute from updateFactory.php:

`result_sql, line 828: REPLACE INTO `geodesic_upgrade_queries` SET `query_id`=1, `strict`=0,`status`=-1`

which sure enuf produces an error in SQL:

![error-3](https://user-images.githubusercontent.com/6634041/186286595-0f4b24d7-0808-4f9e-923f-51b7924a9b89.jpg)

The correct SQL requires that status be quoted:

`REPLACE INTO `geodesic_upgrade_queries` SET `query_id`=1, `strict`=0,`status`='-1'`

**Comment by jonyo** [comment]
Make sure you set strict mode to true in config, I think that is default though.

(Just to rule that out)

That is a pretty old update though so wouldn't be surprised if it doesn't play nice.

**Comment by vicos59** [comment]
> Make sure you set strict mode to true in config, I think that is default though.

Yep, mine is set to '0'

Let me change and try again.

**Comment by vicos59** [comment]
ha ha, yep. That was the issue. Thanks @jonyo 

If only you could have seen the look of disappointment on my face when that error popped up. Like a sad hound dog.

The domain was moved from an old server which didn't use strict mode.
