### ISSUE TITLE
Downloading the project

### ISSUE THREAD

**Issue by ugintl** [geodesicsolutions-community/geocore-community#190]
I want to download the project, but I am confused. On the release page, there are 4 zip files. 

- fusion.zip
- geocore-ce.zip (I know I need to download this one)
- marquee.zip
- tempo.zip

What is the purpose of these folders?

**Comment by vicos59** [comment]
The other 3 are optional template sets. You would install one or more using the admin:

Design->Template Sets->Upload Template Set

**Comment by ugintl** [comment]
@vicos59 so these are themes?

**Comment by blufyremedia** [comment]
@ugintl Yes, Fusion, Marquee & Tempo are alternate basic "themes" (template sets). They are optional to use instead of the default template set, and custom templates can be used as well.

For the purposes of GeoCore, "themes" are called template sets.

**Comment by ugintl** [comment]
It is a big project. Was it a proprietary software in the past?
