### ISSUE TITLE
user_images folder ommitted from built files

### ISSUE THREAD

**Issue by jonyo** [geodesicsolutions-community/geocore-community#32]
Probably the zip commands need to be adjusted in **contrib/build-release**, they are meant to exclude any images added when testing locally in `user_images/` but looks like it even excludes the folder itself.

**Comment by WOs8lfTkz3E5g7I4Lm** [comment]
It looks like the installer allows the user to specify the physical directory for the 'user images'. So, looks like installer should create that directory ? vs including user_images/ in the build?

**Comment by jonyo** [comment]
@WOs8lfTkz3E5g7I4Lm That would end up more work vs. what this PR already does: properly make sure the folder is included in the zip file.
