### ISSUE TITLE
Something wrong with the PHP requirement check if you do not have at least PHP 7.4

### ISSUE THREAD

**Issue by jonyo** [geodesicsolutions-community/geocore-community#45]
I'm dead in the water with the upgrade from Beta-1. Something wrong with the PHP requirement check.

![bug-3](https://user-images.githubusercontent.com/6634041/152710333-7348b558-fda0-47dd-963f-32b411aba062.JPG)

_Originally posted by @WOs8lfTkz3E5g7I4Lm in https://github.com/geodesicsolutions-community/geocore-community/discussions/42#discussioncomment-2122170_

**Comment by jonyo** [comment]
That is the stand alone "fake" requirement page that shows if the actual requirement check fails.  I overlooked this one when I was updating the upgrade script so it is a bit confusing, it should say the requirement is **PHP 7.4** and all the nonsense about ioncube needs to be removed.

**Comment by WOs8lfTkz3E5g7I4Lm** [comment]
I hope you can lower that PHP requirement to PHP 7.2. That is the best my server can do for now and if I need 7.4 I have to just give this up and go look for another product.

**Comment by jonyo** [comment]
@WOs8lfTkz3E5g7I4Lm You'll want to update that version ASAP, it has been EOL since the end of 2020.  As PHP puts it themselves:  https://www.php.net/supported-versions.php

> Users of this release should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities.

And that is regardless of what software you run, you are open to security vulnerabilities running version that old.

That said, the software "might" work with it, just to get past that you can find/replace `7.4.0` with `7.2.0` in `upgrade/index.php` and it should let you through.  But the current requirement 7.4 is there for a reason, as I've said above that version is no longer updated so can have security problems.

**Comment by jonyo** [comment]
@WOs8lfTkz3E5g7I4Lm Did you get a chance to try the suggestion?  For now just change the `7.4.0` in the top of `upgrade/index.php` to `7.2.0` and it should let you pass.

And as mentioned, be sure to update your server when possible since that version of PHP is open to security vulnerabilities (since it is EOL).

**Comment by WOs8lfTkz3E5g7I4Lm** [comment]
Yes, I changed the upgrade script to 7.2.

We can debate for hours about security. I see it as a multi-layered approach and I don't believe that running an older version of PHP is the end of the world. One problem is that PHP is a moving target, by the time you are finished reading this they may be at v126.4. I wrote Perl CGI scripts 24 years ago that still run today.

Also, I use Xenforo which I consider to be a top tier application in that class of software. They still have no issue running on PHP 7.2. When you are a small site operator, you can't always drop what you are doing to update to PHP's latest whim and test all of your legacy production applications to make sure they still work.

All that said, after I get my 7.5.1 upgraded to v20 and I am back in production, then I can safely look at updating my server to more recent PHP. In the mean time I can't risk putting myself out of business.

**Comment by WOs8lfTkz3E5g7I4Lm** [comment]
It was good to have that debate in my head because now I think I can add 7.4, 8.0, and 8.1 to my server w/o disturbing the other versions. Will give that shot in the next few days.

**Comment by jonyo** [comment]
> PHP's latest whim

Just FYI they have a well established release schedule you can see [here](https://www.php.net/supported-versions.php) - each feature release is in main development for 2 years, then "security patches only" for an additional year.

Also if I'm not mistaken, Ubuntu LTS (long term support) version makes backports for security fixes, meaning even though the official php project is not doing security versions, the ubuntu maintainers are.  That was not something I had considered when setting the min version, and it could very well be that your own hosting provider uses something similar to continue applying security patches to the older versions of PHP.

It would be nice if PHP made an LTS version, I don't know the full reason behind their aggressive release and lifecycle policy.  Maybe it is that they are leaving it up to OS maintainers to do backports.  Or maybe it is due to the PHP history, back in the day hosts would run still PHP 4 because that is what scripts used... And scripts would not update their requirement because no hosting was running PHP 5 yet...  So maybe they do the aggressive life cycle to avoid getting into that situation again in the future.

Anyways...  One thought I had, we could do a "hard minimum" and a "soft minimum".  I was not thinking of the fact that some places do keep applying newer security patches, so even if it says PHP 7.2 it is actually PHP 7.2 but with all the security patches released on 7.3 and 7.4 patched on top...

So the thought I had, if you have at least say 7.2, still let you through but show a warning that the PHP version is not supported officially by php.net anymore and we recommend updating to 7.4 if possible.

Do you think that might also help with adoption (and thus, growing the community)?  I can maybe make an issue to implement something like that.

>  It was good to have that debate in my head because now I think I can add 7.4, 8.0, and 8.1 to my server w/o disturbing the other versions. Will give that shot in the next few days.

I can already tell you it will not run on PHP 8.  I have thoughts on that but it can be in its own discussion (heading over to discussion section now 😆 )
