### ISSUE TITLE
Stop the RSS "news" check from the old site

### ISSUE THREAD

**Issue by jonyo** [geodesicsolutions-community/geocore-community#76]
There is a thing that shows "news" on the admin home page, it tries to load an RSS feed from the now shut down old website.

Remove the check.  Maybe leave the parts that allow addons to add their own so that part still works.

**Comment by vicos59** [comment]
src\admin\AJAXController\homeLicense.php

However, I don't see where it displays on the admin home page...Well, I don't see a placeholder for it were it working.

**Comment by jonyo** [comment]
Yeah looks like they removed the spot it used to show, but that is all they did...  Remember when I mentioned to remove stuff when it is no longer used?  Well they did not do that here 😂 ...  Though to be fair, maybe they did not realize how it worked or something, who knows.

This is the part it is still making the call:

https://github.com/geodesicsolutions-community/geocore-community/blob/4756f68c8c9b5007f31b7782379992bfd5c292b7/src/admin/js/home.js#L10-L11

So it is still doing the work every time you view the admin home page, but the results are just ignored since there is no `newsInfo` on the page anymore.

I dug up the history on the original repo, it was "commented out" back in 2016 since it did not change very often.

Since it has been out for a while, we can probably just remove it (don't bother trying to add it back for the sake of showing news added by addons).  I doubt any were taking advantage of it.  But we should stop it from even trying to load, so it doesn't do the extra work every time the home page loads.

**Comment by vicos59** [comment]
This might be relater to #111. Will have to look deeper. The 2 issues may need to be merged in to one.

**Comment by vicos59** [comment]
> it is doing the extra work of attempting to get the news feed, then it just does nothing with the results.

This may be the reason the admin home loads so sluggishly. It is also a potential security risk?

**Comment by vicos59** [comment]
`src\admin\AJAXController\homeLicense.php`

2 applicable functions:

getNews()
getLicenseData() 

getNews calls http://geodesicsolutions.com/latest-software-news-blog.feed?type=rss

**Comment by jonyo** [comment]
> > it is doing the extra work of attempting to get the news feed, then it just does nothing with the results.
> 
> This may be the reason the admin home loads so sluggishly. It is also a potential security risk?

No, it's because the home page is showing so much info, that is a lot of queries.  That is why it uses ajax to load them so the initial page loads, then all the parts come in with AJAX as they load.

**Comment by vicos59** [comment]
Not sure if this should go here or a separate issue. They all seem related.

![software downloads](https://user-images.githubusercontent.com/6634041/156944645-482ec3e3-92c1-4109-89ef-8b8436ef5ba2.JPG)

The download access expires just shows current date.

When you click on the Refresh Downloads Status button, you end up on this URL:

http://localhost:8081/admin/index.php?clear_local_key_cache=1

which displays the Getting Started Checklist.

**Comment by vicos59** [comment]
Coincidentally, right after I did the above, I noticed in my Github Desktop that `src\_geocache\.htaccess` had been deleted. 

Hmmm

**Comment by vicos59** [comment]
src\admin\rss_news_reader.php

calls:

return $tpl->fetch('rss_reader.tpl');

But, I can find no such template.

**Comment by vicos59** [comment]
The Software downloads block is defined in this template:

src\admin\templates\home\downloads.tpl
