### ISSUE TITLE
Reduce official minimum PHP version to 7.2 or 7.0 if possible

### ISSUE THREAD

**Issue by jonyo** [geodesicsolutions-community/geocore-community#77]
The current requirement, 7.4 is there for 2 reasons:

* PHP 7.3 and earlier are "end of life" and no longer officially supported, even for security patches, by PHP. 
* That is the environment I'm testing on in docker so it has the most coverage.

But, at least starting out, we need to allow more people the ability to update to the new community edition that were running older versions.  Especially now in the starting stages of the community, to help it grow more.

To reduce the PHP version, we should do 2 things:

**1. Find a way to check for compatibility issues with earlier versions** - do some research to see if there is a tool that will automatically scan the code to find possible issues with certain PHP versions.  Maybe phpstan or something like that can help.  And/or maybe set up a docker container running the earlier version just to try it out.

**2. Add a warning** - If PHP is at least 7.2 but below 7.4, allow them to continue, but show a warning that it is recommended to update PHP since the version is no longer supported by PHP.

**Comment by jonyo** [comment]
Pushing to beta 5, also we'll need to see if it is possible with the upgrade to Smarty.

**Comment by vicos59** [comment]
After due consideration, I suggest we remove the 7.2 minimum and just go with 7,4.

7.4 only received security updates through Nov 2022 anyway. Too many more important things to do.

**Comment by jonyo** [comment]
That works for me, closing the issue.
