### ISSUE TITLE
Remove "fake" ads in templates that actually link somewhere

### ISSUE THREAD

**Issue by jonyo** [geodesicsolutions-community/geocore-community#81]
I just noticed, in the default templates, there are fake ads.  Find and remove or replace the ads with benign "real fake" ones.  For instance, just at a glance I see what appears to be a real affiliate ad on the listing details page.

Perhaps link them to a wiki article specifically about this - the ads in the templates, and how to either remove them or replace them with your own if you want.  Maybe there is already a wiki article for it, I have not looked, but it should not still have affiliate links for the old company in there.

**Comment by vicos59** [comment]
@jonyo I resolved this issue, but I either not able to upload the changes, or not experienced enough to know how.

I created a new branch on my system and made the changes. When I try to publish it so I can create a Pull Request for you, it tells me that I am small and puny (so the joke's on it because those words mean the same thing).

![fork me im done](https://user-images.githubusercontent.com/6634041/156262335-3c4a9483-ea0d-4059-a9ec-0c4353f3c552.JPG)

**Comment by vicos59** [comment]
@jonyo I created a branch to work on this and it tells me I can not publish it:

![fork me im done](https://user-images.githubusercontent.com/6634041/156262647-19dd5860-c33b-4d42-ba00-5881b01d9c49.JPG)

Cleaned up 4 template files. But, after re-reading your notes, I still need to fix the detail listing page to get those out of the right column. (Actually, I am just replacing them with one generic banner)

**Comment by vicos59** [comment]
\src\admin\getting_started_checks\design_removeDefaultBannersListingDetailsPage.php

This actually checks to see if specific banners have been removed from the following templates as part of the Getting Started scripts:

-- listing_auction.tpl
-- listing_classified.tpl

**Comment by jonyo** [comment]
@vicos59 You have to do the thing where you fork it, make your changes, then do a PR from your fork to the main repo.  Remember the resources linked in the [github wiki](https://github.com/geodesicsolutions-community/geocore-community/wiki)

**Comment by vicos59** [comment]
Well, I thought I did it exactly like I did the last time. Problem is when I do a pull request, it sayeth that I must publish first which gives me the above. Not sure what I missed. Just re-read the docs. Last time I worked on the website repo, not this one. 

![yup](https://user-images.githubusercontent.com/6634041/156264663-c036bb86-af4b-4473-94cf-6930cf9d745e.JPG)

I'll go back over it again and see where I flubbed up.

**Comment by vicos59** [comment]
Changes are ready to go. Just can't get them there.

![bbbbb](https://user-images.githubusercontent.com/6634041/156270775-ba43e169-414d-40b4-bbc9-05b58d64e441.JPG)

**Comment by vicos59** [comment]
@jonyo So, I thought I forked it but I didn't. Fixed that.

The Github Windows complains when I try to create a pull request:

"windows subsystem for Linux has no installed distributions"

Even though last week I successfully created a pull request for the website.

Install a new Ubuntu distribution. Then:

![latest git pita](https://user-images.githubusercontent.com/6634041/156475410-960b5d41-8d97-4d0b-a36c-166ad72e2275.JPG)

I'm not smart enough to know if this is my config or an issue with the geocore repo.

Also, I added a new jpg for the sample banner, but git is not picking it up as a new file in changes.

**Comment by jonyo** [comment]
@vicos59 On the comments - it is good for posterity to keep them up if someone replied already.  Not only for posterity but it may help someone else if they are having similar issues.

Plus, now my comment seems odd just sticking out there answering something that was not asked 😆

**Comment by vicos59** [comment]
@jonyo Yeah, I get it. I had to weigh that vs me looking like less of a dope for having such a time trying to get a simple commit to work. I went with the latter. 😂 

Now, it never happened. Everything went smoothly and you were simply delusional when you replied to a comment that never existed.

**Comment by vicos59** [comment]
All templates sets have now been updated. See #118 & #141
